azure_app_client_id="a9bda07c-7f18-4bc3-bfa0-4d1a9df25ef5"
redirect_uri="https://act.staging-speckle.arup.com/_callback"
project_name="a-carbon-tool"
environment = "dev"
domain = "staging-speckle.arup.com"
